# Generated by Django 5.2.17 on 2026-08-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('picture', models.ImageField(upload_to='character_static/images/buttons/')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters_db.attack')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters_db.button')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='attack',
            name='buttons',
            field=models.ManyToManyField(through='characters_db.AttackButton', to='characters_db.button'),
        ),
        migrations.CreateModel(
            name='ComboAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters_db.attack')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters_db.combo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='attacks',
            field=models.ManyToManyField(through='characters_db.ComboAttack', to='characters_db.attack'),
        ),
        migrations.AddField(
            model_name='combo',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='characters_db.weapon'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pic_url', models.URLField()),
                ('weapons', models.ManyToManyField(related_name='characters', to='characters_db.weapon')),
            ],
        ),
    ]
