# Generated by Django 5.2.17 on 2026-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='pic_url',
        ),
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='character_static/images/legends/'),
        ),
    ]
